[LOCAL]
raw.customers.file.path = data/raw/customers.csv
raw.loans.file.path = data/raw/loans.csv
raw.loan_repayments.file.path = data/raw/loan_repayments.csv
raw.loans_defaulters.path = data/raw/loan_defaulters.csv

[TEST]
raw.customers.file.path = data/raw/customers.csv
raw.loans.file.path = data/raw/loans.csv
raw.loan_repayments.file.path = data/raw/loan_repayments.csv
raw.loans_defaulters.path = data/raw/loan_defaulters.csv

[PROD]
raw.customers.file.path = s3://lendingclub-prod/raw/customers/
raw.loans.file.path = s3://lendingclub-prod/raw/loans/
raw.loan_repayments.file.path = s3://lendingclub-prod/raw/loan_repayments/
raw.loans_defaulters.path = s3://lendingclub-prod/raw/loan_defaulters/
