[LOCAL]
spark.app.name = LendingClubPipeline
spark.sql.shuffle.partitions = 2
spark.driver.memory = 2g

[TEST]
spark.app.name = LendingClubPipeline-Test
spark.sql.shuffle.partitions = 8
spark.driver.memory = 4g

[PROD]
spark.app.name = LendingClubPipeline-Prod
spark.sql.shuffle.partitions = 200
spark.driver.memory = 8g
spark.executor.memory = 8g
spark.executor.cores = 4
spark.sql.parquet.compression.codec = snappy
